server:
  port: 8090

spring:
  main:
    web-application-type: none
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://127.0.0.1:15432/ai-rag-knowledge
    type: com.zaxxer.hikari.HikariDataSource
  ai:
    mcp:
      client:
        request-timeout: 360s
        stdio:
          servers-configuration: classpath:/config/mcp-servers-config.json
    openai:
      base-url: https://apis.itedus.cn
      api-key: sk-wzE9ScCuXky7DkGtBeCfD56675Dc48Ec8d3dCb157d37De62
      embedding-model: text-embedding-ada-002
      embedding:
        options:
          num-batch: 1536
    ollama:
      base-url: http://73c91533f7cc4dc298ae-deepseek-r1-llm-api.gcs-xy1a.jdcloud.com/
      mode:
      embedding-model: nomic-embed-text
      embedding:
        options:
          num-batch: 768

logging:
  level:
    root: info
  config: classpath:logback-spring.xml